[project]
name = "autotrack"
version = "0.1.0"
description = "Audio command transcription tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click",
    "numpy",
    "sounddevice",
    "faster-whisper",
]